# Generated by Django 4.1.13 on 2024-04-21 14:01

import OnlineBlockPosts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBlockPosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=djongo.models.fields.EmbeddedField(model_container=OnlineBlockPosts.models.Content),
        ),
    ]
