services:
 mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
    ports:
      - "7306:7306"

 mongo:
    image: mongo:latest
    ports:
      - "27020:27020"
    volumes:
      - mongo-data:/data/db

volumes:
 mysql-data:
 mongo-data: